Repository RedHatQE/rosa-python-client, pull requests merged in 2023-06, with the labels that each got.

#13 Edit OWNERS file
  OWNERS
Labels: size/XS, branch-main, verified, Approved-by-myakove, can-be-merged

#11 Changed return type from parse_json_response
  rosa/cli.py
Labels: branch-main, size/S, verified, Approved-by-myakove, can-be-merged

#14 raise with proper error when rosa execute failed
  rosa/cli.py
Labels: size/XS, branch-main, verified, Approved-by-rnetser, can-be-merged

#18 Add region to ROSA commands
  rosa/cli.py
Labels: branch-main, verified, Approved-by-myakove, size/M, can-be-merged

#21 Update OWNERS
  OWNERS
Labels: size/XS, branch-main, verified, Approved-by-myakove, can-be-merged, Approved-by-oharan2

#29 Verify that we have AWS credentials before try to login
  poetry.lock
  pyproject.toml
  rosa/cli.py
Labels: branch-main, verified, Approved-by-rnetser, can-be-merged, size/XXL

#31 Use aws_region in rosa_login_logout()
  rosa/cli.py
Labels: size/XS, branch-main, verified, Approved-by-omrirh

#27 Add timeout to execute_command
  rosa/cli.py
Labels: size/XS, branch-main, verified, Approved-by-myakove, Approved-by-rnetser, can-be-merged, Approved-by-omrirh

#36 Set aws credentials os env before change home dir
  rosa/cli.py
Labels: size/XS, branch-main, verified, hold, Approved-by-rnetser, Approved-by-oharan2

#40 Update redhat-qe-cloud-tools to 1.0.7
  poetry.lock
Labels: size/XS, branch-main, verified
