Repository RedHatQE/rosa-python-client, pull requests merged in 2023-08, with the labels that each got.

#71 release-it- use bamper plugin, pyproject update poetry settings
  .release-it.json
  README.md
  VERSION
  poetry.lock
  pyproject.toml
Labels: branch-main, verified, size/L, size/M, ApprovedBy-myakove

#81 Update npm section in release-it file
  .release-it.json
Labels: size/XS, branch-main, verified, ApprovedBy-rnetser

#84 Remove region from login command
  rosa/cli.py
Labels: size/XS, branch-main, verified, can-be-merged, ApprovedBy-myakove
