Repository RedHatQE/rosa-python-client, pull requests merged in 2023-11, with the labels that each got.

#108 Update pre-commit with ruff
  .flake8
  .isort.cfg
  .pre-commit-config.yaml
  pyproject.toml
  rosa/cli.py
  rosa/tests/test_parse_command.py
Labels: branch-main, verified, size/L, can-be-merged, approved-rnetser

#110 flake8-plugins pin to version
  .flake8
  .pre-commit-config.yaml
  rosa/cli.py
  rosa/tests/test_parse_command.py
Labels: size/XS, branch-main, verified, can-be-merged, approved-rnetser

#113 Hash rosa sensitive keys in log
  rosa/cli.py
Labels: branch-main, size/S, verified, can-be-merged, approved-myakove, approved-omrirh
