Repository RedHatQE/rosa-python-client, pull requests merged in 2023-07, with the labels that each got.

#44 Add build command tests
  poetry.lock
  pyproject.toml
  rosa/tests/__init__.py
  rosa/tests/test_parse_command.py
  tox.ini
Labels: branch-main, verified, size/L, Approved-by-rnetser, can-be-merged, Approved-by-oharan2

#46 Cover all rosa commands in tests
  rosa/cli.py
  rosa/tests/conftest.py
  rosa/tests/const.py
  rosa/tests/test_parse_command.py
Labels: branch-main, verified, size/L, Approved-by-rnetser, can-be-merged, Approved-by-omrirh

#52 Get all commands extra values for rosa
  rosa/cli.py
  rosa/tests/conftest.py
Labels: branch-main, verified, size/L, Approved-by-omrirh

#56 Add region name for creds check
  poetry.lock
  rosa/cli.py
Labels: branch-main, verified, Approved-by-myakove, size/L, can-be-merged

#58 Don't logout from rosa
  rosa/cli.py
Labels: branch-main, size/S, verified, Approved-by-rnetser, can-be-merged

#60 build_execute_command when using client and not running on hypershift
  rosa/cli.py
Labels: size/XS, branch-main, verified, Approved-by-myakove, can-be-merged

#62 Login only if not logged in, fix login for openshift-ci
  rosa/cli.py
Labels: branch-main, size/S, verified, Approved-by-rnetser, can-be-merged

#64 remove f-string
  rosa/cli.py
Labels: size/XS, branch-main, verified, Approved-by-myakove, can-be-merged

#66 unify command exeution
  rosa/cli.py
Labels: branch-main, size/S, verified, can-be-merged, ApprovedBy-myakove, CommentedBy-myakove

#68 Fix build_command iteration
  rosa/cli.py
Labels: size/XS, branch-main, verified, can-be-merged, ApprovedBy-myakove

#34 Update parse_help
  rosa/cli.py
Labels: branch-main, verified, size/L, can-be-merged, ApprovedBy-rnetser
