Repository RedHatQE/rosa-python-client, pull requests merged in 2024-03, with the labels that each got.

#165 Fix `rosa edit addon` error
  rosa/cli.py
Labels: size/XS, branch-main, verified, approved-chetna14manku

#171 Add openshift-cluster-management-python-wrapper
  poetry.lock
  pyproject.toml
Labels: branch-main, verified, size/M, can-be-merged, approved-rnetser

#167 Verify rosa is logged in to the correct OCM env, add billing-account to hashed log
  rosa/cli.py
Labels: branch-main, size/S, verified, can-be-merged, approved-myakove

#183 Fix `AttributeError` when calling `is_logged_in` when not logged in
  rosa/cli.py
Labels: size/XS, branch-main, verified
